# -*- coding: utf-8 -*-
"""3D-Photo-Inpainting.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1706ToQrkIZshRSJSHvZ1RuCiM__YX3Bz

**[CVPR 2020] 3D Photography using Context-aware Layered Depth Inpainting**

[project website](https://shihmengli.github.io/3D-Photo-Inpainting/)

- **Prepare environment**
"""

!pip3 install torch==1.4.0+cu100 torchvision==0.5.0+cu100 -f https://download.pytorch.org/whl/torch_stable.html
!pip3 install opencv-python==4.2.0.32
!pip3 install vispy==0.6.4
!pip3 install moviepy==1.0.2
!pip3 install transforms3d==0.3.1
!pip3 install networkx==2.3
!sudo apt install sed

"""- **Download script and pretrained model**"""

# Commented out IPython magic to ensure Python compatibility.
# %cd /content/
!git clone https://github.com/vt-vl-lab/3d-photo-inpainting.git
# %cd 3d-photo-inpainting
!sh download.sh

"""- **Switch off off-screen rendering**"""

!sed -i 's/offscreen_rendering: True/offscreen_rendering: False/g' argument.yml

"""- **Please upload `.jpg` files to `/content/3d-photo-inpainting-master/image/`**
  - You can run this step multiple times to upload multiple `.jpg` files.
"""

# Commented out IPython magic to ensure Python compatibility.
# %cd image
from google.colab import files
uploaded = files.upload()
for fn in uploaded.keys():
  print('User uploaded file "{name}" with length {length} bytes'.format(
      name=fn, length=len(uploaded[fn])))
# %cd ..

"""- **Execute the 3D Photo Inpainting**
  - Note: The 3D photo generation process usually takes about 2-3 minutes or more depending on the available computing resources.
"""

!python main.py --config argument.yml

"""- **The results are stored in the following directories**
  - Corresponding depth map estimated by [MiDaS](https://github.com/intel-isl/MiDaS.git) 
      - E.g. ```/content/3d-photo-inpainting/depth/moon.npy```
  - Inpainted 3D mesh
      - E.g. ```/content/3d-photo-inpainting/mesh/moon.ply```
  - Rendered videos with zoom-in motion
      - E.g. ```/content/3d-photo-inpainting/video/moon_zoom-in.mp4```
  - Rendered videos with swing motion
      - E.g. ```/content/3d-photo-inpainting/video/moon_swing.mp4```
  - Rendered videos with circle motion
      - E.g. ```/content/3d-photo-inpainting/video/moon_circle.mp4```
  
    ![](https://drive.google.com/uc?id=1xBiZAeGfhsoAsG08N5UM8-f993p0G5HF)
"""